version: '3.8'
services:
  app:
    image: teamspeak
    restart: unless-stopped
    ports:
      - ${PORT_VOICE:-9987}:9987/udp
      - ${PORT_QUERY:-10011}:10011
      - ${PORT_FILES:-30033}:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: ${DB_PASS}
      TS3SERVER_DB_NAME: ${DB_NAME:-teamspeak}
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
  db:
    image: mariadb
    restart: always
    ports:
      - ${PORT_VOICE:-30036}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME:-teamspeak}
