version: '3.8'
services:
  ts3:
    build: 
      context: 'https://raw.githubusercontent.com/iTeeLion/teamspeak3_docker/main/Dockerfile'
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    ports:
      - '9987:9987'
      - '10443:10443'
      - '30033:30033'
      - '10010-10080:10010-10080'
    volumes:
      - './config:/opt/ts3/config'
      - './data/data:/opt/ts3/data'
      - './files:/opt/ts3/files'
      - './crashdumps:/opt/ts3/crashdumps'
      - './logs:/opt/ts3/logs'
      
