version: '3.8'
services:
  ts3:
    build: 
      context: 'https://raw.githubusercontent.com/iTeeLion/teamspeak3_docker/main/Dockerfile'
      args:
        UID: ${UID}
        GID: ${GID}
    restart: unless-stopped
    ports:
      - '9987:9987'
      - '10443:10443'
      - '30033:30033'
      - '10010-10080:10010-10080'
    volumes:
      - "./crashdumps:/opt/ts3/teamspeak3-server_linux_amd64/crashdumps"
      - "./logs:/opt/ts3/teamspeak3-server_linux_amd64/logs"
      - "./files:/opt/ts3/teamspeak3-server_linux_amd64/files"
                
