version: '3.8'
services:
  ts3:
    build: 
      context: 'https://raw.githubusercontent.com/iTeeLion/teamspeak3_docker/main/Dockerfile'
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    ports:
      - '9987:9987'
      - '10443:10443'
      - '30033:30033'
      - '10010-10080:10010-10080'
    volumes:
      - './data/t3server.sqlitedb:/opt/ts3/t3server.sqlitedb'
      - './data/t3server.sqlitedb-shm:/opt/ts3/t3server.sqlitedb-shm'
      - './data/t3server.sqlitedb-wal:/opt/ts3/t3server.sqlitedb-wal'
      - './config/query_ip_allowlist.txt:/opt/ts3/query_ip_allowlist.txt'
      - './config/query_ip_denylist.txt:/opt/ts3/query_ip_denylist.txt'
      - './crashdumps:/opt/ts3/crashdumps'
      - './logs:/opt/ts3/logs'
      - './files:/opt/ts3/files'
      
